# 1D Array with Numpy

In [20]:
import numpy as np
import torch

In [8]:
t = np.array([0.,1.,2.,3.,4.,5,6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [9]:
print('Rank of t:', t.ndim)
print('Shape of t: ', t.shape)

Rank of t: 1
Shape of t:  (7,)


In [10]:
print('t[0] t[1] t[2] =  ', t[0],t[1], t[-1])
print('t[0] t[1] t[2] =  ', t[2:5], t[4:-1])
print('t[:2] t[3:] = ', t[:2], t[3:])

t[0] t[1] t[2] =   0.0 1.0 6.0
t[0] t[1] t[2] =   [2. 3. 4.] [4. 5.]
t[:2] t[3:] =  [0. 1.] [3. 4. 5. 6.]


# 2D Array with Numpy

In [14]:
t= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
t

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
print('Rank of t:', t.ndim)
print('Shape of t: ', t.shape)

Rank of t: 2
Shape of t:  (4, 3)


# 1D Array with PyTorch

In [21]:
t = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.,])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [27]:
print(t.dim())
print(t.shape)
print(t.size())
print(t[0], t[1], t[-1])
print(t[2:5],t[4:-1])
print(t[:2],t[3:])

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


# 2D Array with PyTorch

In [29]:
t = torch.FloatTensor([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [30]:
print(t.dim())
print(t.size())
print(t[:,1])
print(t[:, 1].size())
print(t[:, :-1])

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


# Multiplication vs Matrix Multuplication

In [33]:
print()
print('-----------------')
print('Mul vs Matmul')
print('-----------------')
m1= torch.FloatTensor([[1,2],[3,4]])
m2= torch.FloatTensor([[1],[2]])
print('Shape of Matrix 1 :', m1.shape)
print('shape of Matrix 2 :', m2.shape)
print(m1.matmul(m2))

m1= torch.FloatTensor([[1,2],[3,4]])
m2= torch.FloatTensor([[1],[2]])
print('Shape of Matrix 1 :', m1.shape)
print('shape of Matrix 2 :', m2.shape)
print(m1 * m2)
print(m1.mul(m2))


-----------------
Mul vs Matmul
-----------------
Shape of Matrix 1 : torch.Size([2, 2])
shape of Matrix 2 : torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of Matrix 1 : torch.Size([2, 2])
shape of Matrix 2 : torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


# Mean

In [34]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [35]:
# can't use mean() on integers
# what is LongTensr? 
t = torch.LongTensor([1,2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

Can only calculate the mean of floating types. Got Long instead.


In [54]:
t = torch.FloatTensor([[1,2,3,4],[3,4,3,4],[4,5,3,4],[4,5,3,4]])
print(t)
print(t.dim())

tensor([[1., 2., 3., 4.],
        [3., 4., 3., 4.],
        [4., 5., 3., 4.],
        [4., 5., 3., 4.]])
2


In [55]:
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(3.5000)
tensor([3., 4., 3., 4.])
tensor([2.5000, 3.5000, 4.0000, 4.0000])
tensor([2.5000, 3.5000, 4.0000, 4.0000])


# Sum

In [57]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


# Max and Argmax 

In [58]:
t = torch.FloatTensor([[1,2],[3,4]])
t

tensor([[1., 2.],
        [3., 4.]])

In [59]:
print(t.max())

tensor(4.)


In [62]:
print(t.max(dim=0))
print('Max: ', t.max(dim=0)[0])
print('Max: ', t.max(dim=0)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Max:  tensor([1, 1])


In [63]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
