# Veiw

In [ ]:
import numpy as np
import torch

In [11]:
t= np.array([[[0,1,2],[3,4,5]],
             
             [[6,7,8],[9,10,11]]])

In [13]:
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [15]:
print(ft.view(-1,3))
print(ft.view(-1,3).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [19]:
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape) # 2x2x3 = 4x3 = 4x1x3

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


# Squeeze

In [39]:
ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [40]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [41]:
print(ft.squeeze(dim=1))

tensor([0., 1., 2.])


In [42]:
#ft = torch.FloatTensor([[0,2],[1,2],[2,2]])
#print(ft)
#print(ft.shape)
#print(ft.squeeze(dim=1))

tensor([[0., 2.],
        [1., 2.],
        [2., 2.]])
torch.Size([3, 2])


In [52]:
#ft = torch.FloatTensor([[0,1,2]])
#print(ft)
#print(ft.shape)
#print(ft.squeeze(0))
#print(ft.squeeze(0).size())

# Unsqueeze

In [54]:
ft = torch.Tensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [57]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [59]:
print(ft.view(1,-1))
print(ft.view(1,-1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [60]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [61]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


# Type Casting

In [66]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [67]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [69]:
bt = torch.ByteTensor([True,False,False,True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [72]:
print(bt.long())
print(bt.float())


tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


# Concatenate

In [75]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])
print(torch.cat([x,y], dim=0))
print(torch.cat([x,y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


# Stacking

In [76]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])
print(torch.stack([x,y,z]))
print(torch.stack([x,y,z], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [79]:
print(torch.cat([x.unsqueeze(0),y.unsqueeze(0),z.unsqueeze(0)],dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [85]:
#x

In [84]:
#x.unsqueeze(0)

# Ones & Zeros

In [87]:
x = torch.FloatTensor([[0,1,2],[2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [88]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


# In-place Operation

In [89]:
x = torch.FloatTensor([[1,2],[3,4]])

In [90]:
print(x.mul(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [91]:
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
