In [68]:
import torchvision
from torchvision import transforms
from torch.utils.data import DataLoader
import torch.nn.functional as F
import torch.nn as nn
import torch
import torch.optim as optim

In [69]:
from matplotlib.pyplot import imshow

In [128]:
device = 'cuda' if torch.cuda.is_available() else 'cpu' # 이 부분이 설명가능 한지?

torch.manual_seed(777)
if device == 'cuda':
    torch.cuda.manual_seed_all(777)

In [129]:
# size 조정
trans = transforms.Compose([transforms.Resize((64,128))])

train_data = torchvision.datasets.ImageFolder(root='custom_data/origin_data',transform=trans)
data_loader = DataLoader(dataset = train_data, batch_size = 8 , shuffle = True, num_workers=2)
#what is num_workers? 

In [131]:
for num, value in enumerate(train_data):
    data, label = value
    print(num,data,label)
    
    if(label == 0):
        data.save('custom_data/train_data/gray/%d_%d.jpeg'%(num,label))
    else: 
        data.save('custom_data/train_data/red/%d_%d.jpeg'%(num,label))
    
    # 이 부분 다시

0 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE7E0C40> 0
1 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE2F78B0> 0
2 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EB5D1460> 0
3 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE7E0160> 0
4 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE2F7A60> 0
5 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EB5D1460> 0
6 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE4B2130> 0
7 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE7E0160> 0
8 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE2F7DC0> 0
9 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EB5D1460> 0
10 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE4B2370> 0
11 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE7E0160> 0
12 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE2F7A60> 0
13 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EB5D1460> 0
14 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE4B2130> 0
15 <P

159 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE4B2130> 0
160 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE7E0160> 0
161 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EB5D1460> 0
162 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE4B2370> 0
163 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE2F7DC0> 0
164 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE7E0C40> 0
165 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EB5D1460> 0
166 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE4B2370> 0
167 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE2F7A60> 0
168 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE7E0C40> 0
169 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EB5D1BB0> 0
170 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE4B2370> 0
171 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE2F7A60> 0
172 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE7E0C40> 0
173 <PIL.Image.Image image mode=RGB size=128x64 

299 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EB5D1460> 0
300 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EB5D1BB0> 0
301 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE7E0160> 0
302 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE4B2130> 0
303 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE2F7DC0> 0
304 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EB5D1460> 0
305 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE7E0160> 0
306 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE4B2370> 0
307 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE2F7DC0> 0
308 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EB5D1BB0> 0
309 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE7E0160> 0
310 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE4B2130> 0
311 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE2F7DC0> 0
312 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EB5D1460> 0
313 <PIL.Image.Image image mode=RGB size=128x64 

443 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EB5D1BB0> 1
444 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EB5D1460> 1
445 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE7E0C40> 1
446 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE2F7DC0> 1
447 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE4B2370> 1
448 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE7E0160> 1
449 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EB5D1BB0> 1
450 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE2F7A60> 1
451 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE4B2130> 1
452 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE7E0160> 1
453 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EB5D1460> 1
454 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE4B2370> 1
455 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE2F7A60> 1
456 <PIL.Image.Image image mode=RGB size=128x64 at 0x240EE7E0160> 1
457 <PIL.Image.Image image mode=RGB size=128x64 

In [142]:
# size 조정

trans = transforms.Compose([transforms.ToTensor()])
train_data = torchvision.datasets.ImageFolder(root='custom_data/train_data',transform=trans)
data_loader = DataLoader(dataset = train_data, batch_size = 8 , shuffle = True, num_workers=2)
#what is num_workers? 

In [143]:
# 이 부분 파라미터 지정 이유 다시 공부

class CNN(nn.Module):
    def __init__(self):
        super(CNN,self).__init__()
        self.layer1 = nn.Sequential(
            nn.Conv2d(3,6,5),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )
        
        
        self.layer2 = nn.Sequential(nn.Conv2d(6,16,5),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )
        
        
        self.layer3 = nn.Sequential(nn.Linear(16*13*29,120),
            nn.ReLU(),
            nn.Linear(120,2)
        )
        
    def forward(self, x):
        out = self.layer1(x)
#         print(out.shape)
        out = self.layer2(out)
#         print(out.shape)
        out = out.view(out.size(0),-1) # 이부분 사이즈 재구성 이유
#         print(out.shape) 
        out = self.layer3(out)
        return out

In [144]:
net = CNN().to(device)
test_input = (torch.Tensor(3,3,64,128)).to(device) # 이부부 텐서 인풋을 왜이렇게 주었는지
test_out = net(test_input)

In [145]:
optimizer = optim.Adam(net.parameters(),lr=0.00001)
loss_func = nn.CrossEntropyLoss().to(device)

In [162]:
total_batch = len(data_loader)

epochs = 100
for epoch in range(epochs):
    avg_cost = 0.0
    for num, data in enumerate(data_loader):
        imgs, labels = data
        imgs = imgs.to(device)
        labels = labels.to(device)
        optimizer.zero_grad()
        out = net(imgs)
        loss = loss_func(out, labels)
        loss.backward()
        optimizer.step()
        
        avg_cost += loss /total_batch
        
    print('[Epoch:{}] cost = {}'.format(epoch+1, avg_cost))
print('Learning Finished')

[Epoch:1] cost = 0.33863720297813416
[Epoch:2] cost = 0.26268529891967773
[Epoch:3] cost = 0.20186524093151093
[Epoch:4] cost = 0.1556057631969452
[Epoch:5] cost = 0.12044253945350647
[Epoch:6] cost = 0.09384224563837051
[Epoch:7] cost = 0.07344415783882141
[Epoch:8] cost = 0.05790387839078903
[Epoch:9] cost = 0.04664672538638115
[Epoch:10] cost = 0.037346433848142624
[Epoch:11] cost = 0.03099418617784977
[Epoch:12] cost = 0.025922231376171112
[Epoch:13] cost = 0.022093607112765312
[Epoch:14] cost = 0.018845606595277786
[Epoch:15] cost = 0.016467047855257988
[Epoch:16] cost = 0.014399462379515171
[Epoch:17] cost = 0.012666666880249977
[Epoch:18] cost = 0.01123635470867157
[Epoch:19] cost = 0.010341744869947433
[Epoch:20] cost = 0.009028684347867966
[Epoch:21] cost = 0.00811039935797453
[Epoch:22] cost = 0.0073716966435313225
[Epoch:23] cost = 0.006683016195893288
[Epoch:24] cost = 0.0060628908686339855
[Epoch:25] cost = 0.005604189354926348
[Epoch:26] cost = 0.005108905956149101
[Epoch

In [163]:
torch.save(net.state_dict(),"./model/model.pth")

In [164]:
new_net = CNN().to(device)

In [165]:
new_net.load_state_dict(torch.load('./model/model.pth'))

<All keys matched successfully>

In [166]:
print(net.layer1[0])
print(new_net.layer1[0])

print(net.layer1[0].weight[0][0][0])
print(net.layer1[0].weight[0][0][0])

net.layer1[0].weight[0] == new_net.layer1[0].weight[0]


Conv2d(3, 6, kernel_size=(5, 5), stride=(1, 1))
Conv2d(3, 6, kernel_size=(5, 5), stride=(1, 1))
tensor([-0.0243,  0.0594,  0.0658,  0.0722, -0.0987], grad_fn=<SelectBackward>)
tensor([-0.0243,  0.0594,  0.0658,  0.0722, -0.0987], grad_fn=<SelectBackward>)


tensor([[[True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True]],

        [[True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True]],

        [[True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True]]])

In [167]:
trans = torchvision.transforms.Compose([transforms.Resize((64,128)),transforms.ToTensor()])
#transfroms를 두번한 이유가 있나?

test_data = torchvision.datasets.ImageFolder(root='./custom_data/test_data',transform=trans)

In [168]:
test_set = DataLoader(dataset = test_data, batch_size = len(test_data))

In [169]:
with torch.no_grad():
    for num, data  in enumerate(test_set):
        imgs, label = data
        imgs = imgs.to(device)
        label = label.to(device)
        
        prediction = net(imgs)
        correct_prediction = torch.argmax(prediction, 1)== label
        
        accuracy = correct_prediction.float().mean()
        print('Accuracy', accuracy.item())

Accuracy 1.0
